id: P2949DBBE
initial_creation_type: input
source_metadata:
  volume_no_to_title:
    v001: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/KAཀ།
    v002: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཀ།
    v003: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཁ།
    v004: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ག
    v005: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ང་།
    v006: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཅ།
    v007: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཆ།
    v008: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཇ།
    v009: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཉ།
    v010: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཏ།
    v011: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ཐ།
    v012: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ད།
    v013: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/ན།
    v014: KANGYUR (Tibetan Letters/༠༡_འདུལ་བ།/པ།
    v015: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཀ།
    v016: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཁ།
    v017: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ག
    v018: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ང་།
    v019: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཅ།
    v020: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཆ།
    v021: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཇ།
    v022: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཉ།
    v023: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཏ།
    v024: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ཐ།
    v025: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ད།
    v026: KANGYUR (Tibetan Letters/༠༢_འབུམ།/ན།
    v027: KANGYUR (Tibetan Letters/༠༣_ཉི་ཁྲི།/ཀ།
    v028: KANGYUR (Tibetan Letters/༠༣_ཉི་ཁྲི།/ཁ།
    v029: KANGYUR (Tibetan Letters/༠༣_ཉི་ཁྲི།/ག
    v030: KANGYUR (Tibetan Letters/༠༤_བརྒྱད་སྟོང་།/ཀ།
    v031: KANGYUR (Tibetan Letters/༠༥_ཁྲི་བརྒྱད་སྟོང་།/ཀ།
    v032: KANGYUR (Tibetan Letters/༠༥_ཁྲི་བརྒྱད་སྟོང་།/ཁ།
    v033: KANGYUR (Tibetan Letters/༠༥_ཁྲི་བརྒྱད་སྟོང་།/ག
    v034: KANGYUR (Tibetan Letters/༠༦_ཁྲི་པ།/ཀ་_པརྟ་ཏྭོ།
    v035: KANGYUR (Tibetan Letters/༠༦_ཁྲི་པ།/ག་_པརྟ་ཨྣེ། ཅོནྟིནུ
    v036: KANGYUR (Tibetan Letters/༠༧_ཤེར་ཕྱིན་སྣ་ཚོགས།/ཀ།
    v037: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ཀ།
    v038: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ཁ།
    v039: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ག
    v040: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ང་།
    v041: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ཅ།
    v042: KANGYUR (Tibetan Letters/༠༨_དཀོན་བརྩེགས།/ཆ།
    v043: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ཀ།
    v044: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ཁ།
    v045: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ག
    v046: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ང་།
    v047: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ཅ།
    v048: KANGYUR (Tibetan Letters/༠༩_ཕལ་ཆེན།/ཆ།
    v049: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཀ།
    v050: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཁ།
    v051: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ག
    v052: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ང་།
    v053: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཅ།
    v054: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཆ།
    v055: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཇ།
    v056: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཉ།
    v057: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཏ།
    v058: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཐ།
    v059: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ད།
    v060: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ན།
    v061: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/པ།
    v062: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཕ།
    v063: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/བ།
    v064: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/མ།
    v065: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཙ།
    v066: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཚ།
    v067: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཛ།
    v068: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཝ།
    v069: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཞ།
    v070: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཟ།
    v071: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/འ།
    v072: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཡ།
    v073: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ར།
    v074: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ལ།
    v075: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཤ།
    v076: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ས།
    v077: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཧ།
    v078: KANGYUR (Tibetan Letters/༡༠_མདོ་མང་།/ཨ།
    v079: KANGYUR (Tibetan Letters/༡༡_མྱང་འདས།/ཏ།
    v080: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཀ།
    v081: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཁ།
    v082: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ག
    v083: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ང་།
    v084: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཅ།
    v085: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཆ།
    v086: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཇ།
    v087: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཉ།
    v088: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཏ།
    v089: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཐ།
    v090: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ད།
    v091: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ན།
    v092: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/པ།
    v093: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཕ།
    v094: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/བ།
    v095: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/མ།
    v096: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཙ།
    v097: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཚ།
    v098: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཛ།
    v099: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཝ།
    v100: KANGYUR (Tibetan Letters/༡༢_རྒྱུད།/ཞ།
    v101: KANGYUR (Tibetan Letters/༡༣_དཀར་ཆག/ཏ།
created_at: '2022-02-11T15:23:31.975601'
last_modified_at: '2022-02-11T15:23:31.975611'
